### ISSUE TITLE
Incluir pruebas de rendimiento con Gattling

### ISSUE THREAD

**Issue by kilianpg** [Arquisoft/Inci_e3b_modules#13]
Referencias:
- [*Gattling: Quickstart*](https://gatling.io/docs/current/quickstart)
- [*Gattling's Maven Plugin*](https://gatling.io/docs/current/extensions/maven_plugin)
- [*Gatling-maven-plugin-demo*](https://github.com/gatling/gatling-maven-plugin-demo)
- [*Gattling's Maven Archetype*](https://gatling.io/docs/2.3/extensions/maven_archetype)
- [*Performance Testing vs. Load Testing vs. Stress Testing*](https://www.blazemeter.com/blog/performance-testing-vs-load-testing-vs-stress-testing)
- [*Tutorial de Gatling y Maven*](https://www.federico-toledo.com/tutorial-de-gatling-y-maven)

**Comment by dalvgui** [comment]
Las pruebas de gatling tanto los .scala y los resultados los dejamos ubicados en onedrive [aquí](https://unioviedo-my.sharepoint.com/:f:/g/personal/uo237030_uniovi_es/Ek-_1ijGt5VFq29k0OxbnzgBQFVJQ31sza48palT-emTsQ?e=gvvxEw).
