### ISSUE TITLE
Unificar versiones POM, módulo Agents

### ISSUE THREAD

**Issue by miguelms95** [Arquisoft/Inci_e3b_modules#18]
Comprobar que funciona con la misma versión en las dependencias del POM, comprobar en: [POM.xml de inci_modules](https://github.com/Arquisoft/Inci_e3b_modules/blob/master/InciTest_e3b/pom.xml#L19)

**Comment by Gemeto** [comment]
Se han unificado las versiones del POM de inci_test y Agents
