### ISSUE TITLE
Integración de los repositorios de cada componente utilizando git submodule

### ISSUE THREAD

**Issue by kilianpg** [Arquisoft/Inci_e3b_modules#2]
Los repositorios a integrar son:

- Módulo de carga de usuarios: [Loader_e3b](https://github.com/Arquisoft/Loader_e3b).
- Módulo de consulta y gestión de agentes: [Agents_e3b](https://github.com/Arquisoft/Agents_e3b).
- Módulo de gestión y carga de incidencias: [InciManager_e3b](https://github.com/Arquisoft/InciManager_e3b).
- Módulo de análisis y cuadro de mandos: [InciDashboard_e3b](https://github.com/Arquisoft/InciDashboard_e3b).

Referencias:
- [Git Tools - Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

**Comment by miguelms95** [comment]
Diría que esto ya está, módulos importados. Solo quedaría cuando se cambien cosas importantes en los repositorios enlazados, ejecutar este comando desde la directorio raiz:
`
git submodule foreach git pull origin master
`

**Comment by kilianpg** [comment]
Se ha incluido un fichero POM de Maven con la descripción de la jerarquía de submódulos del  proyecto para facilitar el trabajo con los entornos de desarrollo (IDE's) de cada contribuidor.
