### ISSUE TITLE
Rellenar test integración

### ISSUE THREAD

**Issue by miguelms95** [Arquisoft/Inci_e3b_modules#6]
He creado el esqueleto de todo el proyecto de test de integración:
https://github.com/Arquisoft/Inci_e3b_modules/blob/master/TestIntegration_e3b/src/test/java/TestIntegration.java

Ahora hay que rellenarlo, me parece que está todo bien documentado (que debería hacer cada método de test). Obviamente hay que probar más cosas, pero esto es un esquema para comenzar.

**Comment by Gemeto** [comment]
El test que envia una incidencia desde InciManager ya esta listo.
